## Server Configuration
SERVER_NAME: "codebase-go-rest-lite"
SERVER_IP: "0.0.0.0"
SERVER_PORT: "3000"
SERVER_STORE_PATH: "./share/store"
SERVER_UPLOAD_PATH: "./share/upload"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "info"

## Router Configuration
ROUTER_BASE_PATH: ""

## Cryptography Configuration
CRYPT_PRIVATE_KEY_FILE: "./share/private.key"
CRYPT_PUBLIC_KEY_FILE: "./share/public.key"
